import type { Metadata } from 'next'
import { Montserrat,Poppins } from 'next/font/google'
import './globals.css'

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: "--primary-font",
  weight:['700']
})

const poppins = Poppins({
  subsets: ['latin'],
  variable: "--secondary-font",
  weight:'900'
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${poppins.variable}`}>{children}</body>
    </html>
  )
}
